### ISSUE TITLE
Правки в заголовках

### ISSUE THREAD

**Issue by bzaar** [morpher-ru/gramdict#1]
* Добавить все имеющиеся в тексте заголовки и подзаголовки в "Содержание" на странице http://gramdict.ru

* Назначить заголовкам теги, соответствующие их уровню вложенности в "Содержании" ("Предисловие", "Грамматические сведения" - h1).

**Comment by bzaar** [comment]
Под текстом имеется в виду весь текст на сайте в файлах .cshtml.

**Comment by bzaar** [comment]
Наверное, я недостаточно ясно выразился. Смысл задачи в том, чтобы добавить всем заголовкам тэг id:

&lt;h3 id=&quot;header5&quot;&gt; Заголовок &lt;/h3&gt;

И потом сослаться на него из содержания:

&lt;li&gt;&lt;a href=&quot;how-to-use#header5&quot;&gt;заголовок &lt;/a&gt;&lt;/li&gt;

Если заголовка нет в Содержании, то добавить его туда.

**Comment by bzaar** [comment]
Please also rename index.cshtml to contents.cshtml or you will get conflicts when merging with https://github.com/morpher-ru/gramdict/pull/8/files.

**Comment by Erasiloco** [comment]
ok

**Comment by bzaar** [comment]
У некоторых заголовков может быть неправильный уровень (например, h2 вместо h3). Нужно исправить в соответствии с уровнем этого заголовка в "Содержании".

**Comment by Erasiloco** [comment]
check please
