### ISSUE TITLE
Eliminate the seam in the background image

### ISSUE THREAD

**Issue by bzaar** [morpher-ru/gramdict#100]
![image](https://user-images.githubusercontent.com/4028922/63302404-e4dc2a00-c2d4-11e9-9099-24d9d329028f.png)

Mirror the image vertically and append to the existing image.

**Comment by GoToNightmare** [comment]
![image](https://user-images.githubusercontent.com/34166246/83796191-0b2f5280-a6ba-11ea-9cd1-da1cedf1afe7.png)
looks mediocre tbh, anyways pr created
https://github.com/morpher-ru/gramdict/pull/141

**Comment by bzaar** [comment]
Better  than it was before - thanks! Estimate 0.5 hours?

**Comment by bzaar** [comment]
Still can see the seam:

![image](https://user-images.githubusercontent.com/4028922/85287988-f3631700-b48c-11ea-9447-e5b7f3dc5025.png)


https://gramdict.ru/preface/#variants-creep

**Comment by bzaar** [comment]
Can't see it anymore. Probably needed Ctrl-F5 before.
