### ISSUE TITLE
Scripts are slow to load

### ISSUE THREAD

**Issue by bzaar** [morpher-ru/gramdict#112]
Open http://gramdict.ru
Notice how long it takes for the search/menu bar to appear. Normally, the html text and the picture load instantaneously, while the menu bar can take up to 10 seconds to appear. Sometimes it errors out:

![image](https://user-images.githubusercontent.com/4028922/70378898-09105500-191e-11ea-9e23-aad9fcd2b2b9.png)

**Comment by GoToNightmare** [comment]
![image](https://user-images.githubusercontent.com/34166246/83792284-47f84b00-a6b4-11ea-9601-4d5d9995a66b.png)
Hard refresh, probably fixed?

**Comment by bzaar** [comment]
Yeah.. probably. Thanks for looking at it.
