### ISSUE TITLE
Поправить сноски

### ISSUE THREAD

**Issue by bzaar** [morpher-ru/gramdict#3]
Сейчас сноски расположены группами (например, [здесь](https://github.com/morpher-ru/gramdict/blob/master/gramdictru/Pages/conjugation/models.cshtml#L77)), а не так, как в бумажном словаре.

Расположить текст сносок (class="footnote") чуть ниже параграфа, который на них ссылается, например, перед следующим подзаголовком.

Сделать цифры сносок гиперссылками.

**Comment by Vezirmir** [comment]
Изменить все сноски которые есть на сайте?

**Comment by bzaar** [comment]
Все, которые расположены слишком далеко от текста, который на них ссылается - иногда даже в другом файле. Т.е. нужно примерно так:

&lt;h2&gt;Some heading&lt;/h2&gt;

&lt;p&gt; Blah blah see &lt;sup&gt;1&lt;/sup&gt; &lt;/p&gt;
&lt;p&gt; Blah blah see &lt;sup&gt;2&lt;/sup&gt; &lt;/p&gt;

&lt;p class=&quot;footnote&quot;&gt;&lt;sup&gt;1&lt;/sup&gt; Blah blah&lt;/p&gt;
&lt;p class=&quot;footnote&quot;&gt;&lt;sup&gt;2&lt;/sup&gt; Blah blah&lt;/p&gt;

&lt;h2&gt;Next heading&lt;/h2&gt;

**Comment by Vezirmir** [comment]
1. http://www.gramdict.ru/declension/symbols на этой странице сноска 7. в тексте не используется например. как поступать в этом случае?

**Comment by bzaar** [comment]
Возможно, она где-то в другом файле используется. Посмотри пожалуйста
сканы. Все сноски должны где-ио использоваться.

**Comment by Vezirmir** [comment]
Тогда я по скану сделаю сноски, потому что там различий много.
