### ISSUE TITLE
Add anchor links

### ISSUE THREAD

**Issue by bzaar** [morpher-ru/gramdict#69]
Please add clickable links that appear when you hover over a heading or paragraph, e.g. at http://morpher.ru/ws3/#declension:

![image](https://user-images.githubusercontent.com/4028922/57989754-80bc8680-7a97-11e9-9237-16fbc61dd94d.png)

Tags to include are p, li, h1...h6 having an id attribute.

**Comment by bzaar** [comment]
Please use this symbol for the link: §

**Comment by my-official** [comment]
https://github.com/morpher-ru/gramdict/pull/73
