### ISSUE TITLE
Selecting all symbols should yield all entries

### ISSUE THREAD

**Issue by bzaar** [morpher-ru/gramdict#99]
Currently it's not the case:

![image](https://user-images.githubusercontent.com/4028922/63300819-02a79000-c2d1-11e9-97fa-fd56689a28e0.png)

http://dev.gramdict.ru/search/*?symbol=%D1%81%D0%B2,%D0%BD%D1%81%D0%B2,%D1%81%D0%B2-%D0%BD%D1%81%D0%B2,%D0%BF%D1%80%D0%B5%D0%B4%D0%B8%D0%BA%D0%B0%D1%82%D0%B8%D0%B2%D0%BD%D0%BE%D0%B5%20%D0%BC%D1%81,%3Ci%3E(%D0%BD%D0%B5%D1%82)%3C%2Fi%3E,%D0%BC%D0%B5%D0%B6%D0%B4.,%D0%B2%D0%B2%D0%BE%D0%B4%D0%BD.,%D1%81%D1%80%D0%B0%D0%B2%D0%BD.,%D0%BF%D1%80%D0%B5%D0%B4%D0%BB.,%D1%84.,%D1%81%D0%BE%D1%8E%D0%B7,%3Ci%3E%D1%81%D0%BC.%3C%2Fi%3E,%3Ci%3E%D0%A0.%20%D0%BC%D0%BD.%3C%2Fi%3E,%D1%87%D0%B0%D1%81%D1%82.,%D0%BF%D1%80%D0%B5%D0%B4%D0%B8%D0%BA.,%D0%BC%D0%BD.%20%D0%BD%D0%B5%D0%BE%D0%B4.,%D0%BC%D0%BD.%20%D0%BE%D0%B4%D1%83%D1%88.,%D0%BC%D0%BD.%20%3Ci%3E%D0%BE%D1%82%3C%2Fi%3E,%D0%BC%D0%BD.,%D0%BC%D0%BE-%D0%B6%D0%BE,%D0%B6%D0%BE%E2%81%BA,%D0%BC%D0%BE%E2%81%BA,%C2%A71,%C2%A72,%D1%87%D0%B8%D1%81%D0%BB.,%D1%87%D0%B8%D1%81%D0%BB.-%D0%BF,%D0%BC%D1%81-%D0%BF,%D0%BC%D1%81,%D1%81%D0%BE,%D0%B6%D0%BE,%D0%BC%D0%BE,%D0%BC,%D0%B6,%D1%81,%D0%BD,%D0%BF

**Comment by GoToNightmare** [comment]
done in #136

**Comment by bzaar** [comment]
Пока PR не принят, рано закрывать задачу.
